### ISSUE TITLE
[Sozialpass] Setup a switch for the app language

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#1175]
**Is your feature request related to a problem? Please describe.**
As a user I want to be able to switch the app language without having to switch the whole system language.

**Describe the solution you'd like**
There should be a button/toggle to select the current app language. The possible language options should depend on the available languages configured in the build configs (#1176).

**Describe alternatives you've considered**
Always use the system language.

**Additional context**
Part of #1174.

**Design Issue:**
There is currently no overflow menu or settings menu yet. the main challenge is to find an appropriate place for it and place there the language switch

**Comment by hauf-toni** [comment]
design proposal can be found 📌 [here](https://www.figma.com/file/SDoGnXIjCCXpE1tAAJkRVc/entitlementcard?type=design&node-id=168%3A393&mode=design&t=XghNzvLzY8s7XuRp-1). due to the limited time for development, this proposal may have to be adapted in order to be realisable in a shorter period of time. please feel free to give me more information and comment in figma.
