### ISSUE TITLE
Touch animation displayed after back navigation

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/entitlementcard#1198]
**Describe the bug**
In the about screen in the frontend the touch animation for clicking on a `ContentTile` happens only after navigating back to the about screen instead of instantly.

**To Reproduce**
1. Go to About
2. Click on License 
3. Go back
4. See touch animation for `License` being shown 

**Expected behavior**
The touch animation is not done after a back navigation.

**Screenshots**
https://github.com/digitalfabrik/entitlementcard/assets/29095487/98ff28bb-a3e2-4447-bf7f-075b1d3a0cd3

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 10 Pro
 - OS: Android 14

**Additional context**
See #1197 for a short discussion on this topic. Apparently it only happens on Android.

**Comment by seluianova** [comment]
This happens because the content loads too fast after clicking.
If you tap the item a little longer, you can see the animation before the content opens, not after.

The same behavior can be observed on the Search page, when you open the store details.

I can see 2 options to change that:
- Open the content longer, by waiting for ~500 ms before opening the page (not nice, oder?);
- Remove the splash animation at all.

But to be honest the current behavior doesn’t look like an issue to me.
Even if we see the splash after the return, it just Indicates that the item has been touched.
Do we really want to fix that?

**Comment by f1sh1918** [comment]
i've also investigated some time and its really minor. i wouldn't put effort in it

**Comment by seluianova** [comment]
@f1sh1918 shall we close it or move to the backlog?

**Comment by f1sh1918** [comment]
close

**Comment by f1sh1918** [comment]
not worth to fix it
