### ISSUE TITLE
Create a mapping-database table for linking koblenz-users-table and cards-table

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/entitlementcard#1424]
**Is your feature request related to a problem? Please describe.**
we need a new table, which links the koblenz-users-table with the card that is connected to the entry in the koblenz users table.

**Describe the solution you'd like**
- Create a new table with two fields:
- id of the cards table
- id of koblenz-users-table
- extend createCard function->fill this table with the particular ids 

**Describe alternatives you've considered**
Add a field "cardID" to the koblenz users table

**Comment by seluianova** [comment]
**Questions**:
Do we want to allow multiple cards to be created for the same user?
When an additional card is created, should we keep the old cards active or we want to deactivate them?

**Comment by seluianova** [comment]
@ztefanie @f1sh1918 
Could you please clarify if there is a specific reason why we want to store the relation in a separate mapping table?
I believe this approach is usually used for many-to-many relationships. While we have a one-to-many relation in our case.

> Describe alternatives you've considered:
> Add a field "cardID" to the koblenz users table

I would create an entitlements_id column in cards table.
Because for one user we can have many cards (one active, others revoked).
Any objections to that?

**Comment by f1sh1918** [comment]
no i think thats fine. 
i think the reason was that we didn't want to adjust the card table with another optional id
the only thing we have to ensure later in the "extend card" function is that the old card will be revoked after new card was activated but that should work with this solution

**Comment by ztefanie** [comment]
yes thats fine.
