### ISSUE TITLE
Can not activate by tapping on activation code

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/entitlementcard#1480]
**Describe the bug**
I created a 'ehrenamts' card, copied the pdf to real android device and emulator, open it with pdf reader.
On device nothin happens
On emulator get message 'Aktivierung nur in der App möglich ...'

**Expected behavior**
App should open and shows the aktivated QR-code Variante 2

**Comment by f1sh1918** [comment]
@Docmale can you add some specifications like device model, os version and the pdf reader you used

**Comment by f1sh1918** [comment]
i've tested couple of times in browserstack and it seem to happen only on some devices/android versions

How this can be checked
1. Install app on device
2. Go App Info
3. Advanced
4. Open Default
5. Check supported links (staging and production url should be included)

**Comment by f1sh1918** [comment]
@Docmale 
i believe the issue is that by installing the apks attached from release that they are unsigned and by default the associated links are not trusted.
If you install an app from the play store (signed apk) or use a signed apk file, this should not happen.

Not sure if its worth the effort to provide signed apk just for setting these links default. But you could just recheck this issue with the apk i send you

**Comment by Docmale** [comment]
Since the mechanism does not work with every PDF reader/viewer and system version, I am closing the bug. However, the text should include a note that clicking does not always work and an alternative should be given.
