### ISSUE TITLE
Notify release for native and web

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1521]
**Is your feature request related to a problem? Please describe.**
As a dev i want to deploy for native and web/backend separately. Therefore we need to adjust the notify release job because we assume that `deb` and `apk` packages are available

**Describe the solution you'd like**
- Pass a parameter that defines which artifacts must be available to upload depending on which platform you release

**Comment by steffenkleinle** [comment]
This will be fixed by https://github.com/digitalfabrik/app-toolbelt/pull/15. Instead of passing a parameter to define which assets should be uploaded, I chose to just made the upload more robust and correctly handle if an empty list of files is passed. I tested this here: https://app.circleci.com/pipelines/github/digitalfabrik/entitlementcard/6029/workflows/38c8d3dd-911f-4e2c-a475-52322ab9df01/jobs/43140
