### ISSUE TITLE
Validation error when entering the date of birth from the keyboard on the self-service portal

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/entitlementcard#1795]
**Describe the bug**
Cannot create a card if the birthday is entered from the keyboard because of the validation error even if the date is valid

**To Reproduce**
1. Open http://localhost:3000/erstellen
2. Enter valid birthday using the keyboard --> **field validation error is displayed**

**UPD**. It seems that if the date is selected using the calendar, it is also not possible to submit the form, but in this case the validation error only occurs after clicking the 'KoblenzPass erstellen' button

**Expected behavior**
If the entered date is valid, it should be accepted

**Screenshots**
![image](https://github.com/user-attachments/assets/77770b44-febe-4adc-ae33-4a7fd345bb08)

**Desktop (please complete the following information):**
Reproduced in Desktop and Mobile Chrome browsers

**Additional context**

**Comment by f1sh1918** [comment]
@seluianova I can not reproduce this on chrome


https://github.com/user-attachments/assets/95f3a868-0ada-495e-a819-0f28e2e0ea0c


https://github.com/user-attachments/assets/279347c4-dcab-4d1e-81df-e4703e77cf77

But i found this issue that may be created due to some conditional change in `createKoblenzPass` function.
Second toast shouldn't be displayed

<img width="497" alt="image" src="https://github.com/user-attachments/assets/8bf80485-9fff-4b34-bad2-f89060c1280f">

**Comment by seluianova** [comment]
I’ve just double checked and it is still reproduced for me (recent main).
I think we could take a look at it at the conference

**Comment by f1sh1918** [comment]
alright no clue if thats browser dependent on mac/linux (i have recent chrome update)

**Comment by f1sh1918** [comment]
did you run `npm i` on root folder?

**Comment by seluianova** [comment]
> did you run npm i on root folder?

Yes but I will do again at the conference, already packing my stuff 

> Is there any additional error message?

No, looks like on the screenshot I posted

**Comment by steffenkleinle** [comment]
I can also reproduce this issue :/ It is due to locale settings on the device :) Will open a PR.
