### ISSUE TITLE
Introduce proper linting rules

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#413]
**Is your feature request related to a problem? Please describe.**
Right now we do not have linting rules for example for unused imports. I suppose there are many more cool and beneficial linting rules.

Lightweight refactoring can also be done in this task.

**Comment by klinzo** [comment]
So actually we already have linting enabled: [flutter_lines](https://pub.dev/packages/flutter_lints) is used which is enabled by default in new projects. It seems to be relatively loose though. `unused_imports` is actually not a linting rule but a regular analysis issue which is also already enabled (as `info` and not as `error` though).

The most popular alternative by far seems to be [lint](https://pub.dev/packages/lint). The default configuration shows 704 issues ()
Most issues are because of:
* 424 because of `require_trailing_commas`
* 134 because of `prefer_final_locals`
which only leaves 146 other issues. I think this is reasonable enough to fix so I would go with `lints` package. What do you think @maxammann @Schedulaar?
