### ISSUE TITLE
App was rejected on F-Droid

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#549]
A few weeks/months ago the Ehrenamtskarte was more or less silently removed from the F-Droid store.
The reason for this is that our build process used proprietary Android libraries by Google.
Those libraries were never delivered to F-Droid users, as they were stripped during packaging.

Initial F-Droid merge request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10382
Related issue of another app: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991

**Comment by maxammann** [comment]
@IzzySoft 

> OK, then `s/if/when/` wink Should the need arise. Though it's be sad if a project dedicated to Ehrenamt would only be available via walled gardens and thus make it unavailable to some of us. Which is why I offer to take it into my repo as compromise.

Thanks! 

Yes, I'd personally love to have it on F-Droid. But somebody has to put effort into maintaining it for F-Droid.

As a developer at Digitalfabrik I think it is better to include all of Digitalfabrik's apps in this discussion and: Either all apps or none of the apps is on F-Droid.
The biggest concern on my side is that we will never have proper insights on how many users are using the apps through F-Droid. Without this information its difficult to justify development time and resources.

**Comment by maxammann** [comment]
Personally, I don't really agree with the F-Droid maintainers to remove this app. That's basically why I don't want to invest personal/free time into bringing the app again to F-Droid.
I think the exclusion is driven by ideology and not by practical reasons.

**Comment by IzzySoft** [comment]
> As a developer at Digitalfabrik I think it is better to include all of Digitalfabrik's apps in this discussion and: Either all apps or none of the apps is on F-Droid.

Multiple options here:

* bring them all there
* split them across repos (those meeting F-Droid's inclusion criteria go there, the others to a different repo)
* set up your own F-Droid repo (not as hard to accomplish as you might think, see e.g. [Setting up a simple binary F-Droid repo](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo) and its follow-up [Extend the „simple binary repo“: Screenshots & more](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo-2))
* let's see if we can bring them to my repo

The 3rd option might be the one fitting you best, as you remain in full control – though the first option has more user-trust.

> The biggest concern on my side is that we will never have proper insights on how many users are using the apps through F-Droid. Without this information its difficult to justify development time and resources.

If you need to justify that, well… you could ask for voluntary information (like a popup after the app has been opened for the 10th time, stating your needs and asking for a single ping-back). With us privacy folks, one first needs to earn a lot of trust before we allow you a "tracker" – and most won't be fine with a proprietary one.

> Personally, I don't really agree with the F-Droid maintainers to remove this app.

I didn't follow that in detail, but IIRC it was due to a non-free dependency. And in that case the reasoning is perfectly clear: it violates the inclusion criteria. And there are no exceptions in such a case; if we make one exception here, why wouldn't there be another one there? And where's the line? No "Der Zweck heiligt die Mittel" with this, sorry.

On a different topic: It never hurts to show the card at places not advertising acceptance. Got a discount today on a boat trip, as the ships there are partially funded by the Freistaat Bayern. Nice :smiley:

**Comment by IzzySoft** [comment]
Oh, I just noticed this isn't the original thread – and it has a different initial post:

> Those libraries were never delivered to F-Droid users, as they were stripped during packaging.

That would be weird. IIRC the team investigated the resulting APK and found things there. As said, the discussion was a bit lengthy and I didn't follow it entirely (some other app(s) was/were affected the same way). The corresponding post is [this one](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991#note_938539763) where one of the core members ran an in-depth build analysis. I'd basically go with [Hans' conclusion](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991#note_942614609) (it would need an Anti-Feature but were allowed to stay) – but I'm no developer and thus lack the arguments there. If I could follow the entire thing to its last cell and still have the same opinion, I'd put up the argument.

That said, you have the reason why I'd accept it into my repo if you want to have it there. Concerning the other apps of Digitalfabrik you've mentioned, we must see one-by-one if they meet the (less strict) criteria of my repo.

**Comment by maxammann** [comment]
> The corresponding post is [this one](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991#note_938539763) where one of the core members ran an in-depth build analysis.

I actually never saw that analysis before. There was another which had different results before. I'm a little bit shocked that the ehrenamtskarte app was removed, without officially letting us know the exact reasons via email. I was not aware that maplibre is the actual problem.
Also discussion the ehrenamtskarte app in some random other apps thread is not ideal.

So basically the exclusion is based on miss-communication. I'm happy to exclude the mentioned class files, which should be trivial (after some investigation).

> If you need to justify that, well… you could ask for voluntary information 

This is out of scope for us. Implementing such lightweight tracking is additional effort we can not really justify.

> On a different topic: It never hurts to show the card at places not advertising acceptance. Got a discount today on a boat trip, as the ships there are partially funded by the Freistaat Bayern. Nice smiley

Yes :D I've heared that a few times already! Should try it myself!

---


So all in all, I would be happy about a report about the exclusion of the ehrenamtskarte. If we get that (via email or a Github issue here), we can evaluate the effort and implement it or look for alternatives.

I was really confused because I thought we were excluded because the **build process** required to download a library from Google, without including it in the final artifact. I was never aware or problems related to maplibre.

**Comment by IzzySoft** [comment]
I was a bit confused about that myself, but thought I must have missed a part (as pointed out, not being an Android developer myself I felt lost in some places). Like Hans wrote: If it just *references* some non-free things, it should at most get the NonFreeDep Antifeature (if those parts are really needed for the functionality) and that's it.

> So basically the exclusion is based on miss-communication. I'm happy to exclude the mentioned class files, which should be trivial (after some investigation).

That'd be great! If you'd open an issue for that here (for you to solve – i.e. the implementation tasks) I could try to point a team mate to that so you'd get feedback on whether that'd be sufficient (or what else might be amiss). Once solved it can be carried over to F-Droid again to re-enable the app.

> I would be happy about a report about the exclusion of the ehrenamtskarte.

As I cannot really follow that, I'm afraid I cannot give you such report. All I noticed was Ehrenamtskarte being suddenly dragged in; I then ran my scanner and stated there was no such library included but the code had just some references (potential calls) to them. which *might* justify NonFreeDep, but not more.

> I thought we were excluded because the build process required to download a library from Google

In that case, the initial MR for including your app would have failed.

> I was never aware or problems related to maplibre.

And I'm not even sure if maplibre doesn't just use the same class names (like microG does). But again, I'm no Android dev – so I might not be exactly the right person to argue the details. Which is why I proposed to have a dedicated issue here for that – and I see if I can get a team member to take a look.

**Comment by IzzySoft** [comment]
@maxammann take a look [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1004#note_1035997171). As quite a bunch of apps seems to be affected by the very same issue, this became quite a storm. Looks like maplibre has tackled the issue already. Maybe that could help re-establish Ehrenamtskarte?

**Comment by maxammann** [comment]
> @maxammann take a look [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1004#note_1035997171). As quite a bunch of apps seems to be affected by the very same issue, this became quite a storm. Looks like maplibre has tackled the issue already. Maybe that could help re-establish Ehrenamtskarte?

Not sure if maplibre changed anything. That thread is quite long, so I'm not sure what exactly the issue is, or in which version it was fixed.

**Comment by IzzySoft** [comment]
If I understood this correctly, a newer version of maplibre solved it – but I totally lost track if some additional adjustments were needed. Indeed that issue got quite long – too long to be followed easily if you were not fully involved from the start, I'm afraid. Which is why I linked to the comment I hoped to have the most relevant notes for you…

**Comment by maxammann** [comment]
We are currently not planning to release on F-Droid. We might upload FLOSS APKs to Github Releases in the future.

**Comment by IzzySoft** [comment]
@maxammann please drop me a note when the APKs are available, so I can list the app in my repo again. Looking forward to that!

**Comment by maxammann** [comment]
Sure, we will let you know! I would estimate that will be around April 2023. We are working on another app which is called "Nürnberger Sozialpass". That will use the same technical foundations.

After that is done we can do the low-prio stuff :)

**Comment by IzzySoft** [comment]
Hi @maxammann, I see you started tagging releases again. Is there any hope the APKs will soon be attached there as well? :smiley:

**Comment by maxammann** [comment]
cc @sarahsporck @f1sh1918 @michael-markl

**Comment by linsui** [comment]
We have removed the metadata from fdroiddata since all versions are diabled.

**Comment by michael-markl** [comment]
It seems, this is related: https://gitlab.com/fdroid/fdroiddata/-/commit/cba1111cbca58b5f069325da6be61fb61ea31e58

**Comment by IzzySoft** [comment]
@maxammann @sarahsporck @f1sh1918 @michael-markl any news concerning the APK – so I could see to have the listing in my repo updated (which still has the one with the old applicationId)?

**Comment by IzzySoft** [comment]
@maxammann @sarahsporck @f1sh1918 @michael-markl I see there was a new release 2 weeks ago, but no APK attached :cry: Is this still planned for the folks outside PlayStore, or do we have to abandon all hope?

**Comment by f1sh1918** [comment]
> @maxammann @sarahsporck @f1sh1918 @michael-markl I see there was a new release 2 weeks ago, but no APK attached :cry: Is this still planned for the folks outside PlayStore, or do we have to abandon all hope?

We gonna provide apks soon.

**Comment by f1sh1918** [comment]
Usually it takes around two weeks until everything was tested and shipped from beta to production.
you can find the apks now on the release page. thx for reminder.
https://github.com/digitalfabrik/entitlementcard/releases/tag/v.3.2.0

**Comment by IzzySoft** [comment]
Thanks!
