### ISSUE TITLE
Akzeptanzstellen Import for Nurnberg

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#688]
**Is your feature request related to a problem? Please describe.**
We need to write an importer for Nuernberg which reads from a CSV/Excel file and import the data into the database.

We should import it from file downloadable at some URL such that updates to the data is simple.

The current excel file is: https://nextcloud.tuerantuer.org/index.php/apps/onlyoffice/3258700

**Describe the solution you'd like**
We could think about first converting the CSV to JSON as JSON might be a clearer format to support in the input (tabs, delimiters etc. are non ambiguous in JSON).

Download the current data from: 
* https://data.entitlementcard.app/2022-12%20Akzeptanzpartner-daten.csv
* https://data.entitlementcard.app/2022-12%20Akzeptanzpartner-daten.ods
* https://data.entitlementcard.app/2022-12%20Akzeptanzpartner-daten.xlsx

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by dkehne** [comment]
The categories in the above files are not the current ones because i was not able to edit the sheet (because it was protected). @maxammann can you update the data in your post above? IDs and amount stays the same but labels are different.

<html><body>


Kategorie | Kategorienbeschreibung | Kurzbeschreibung
-- | -- | --
0 | Mittagstische | Mittagstische
1 | Kleidung/Gebrauchtes | Kleidung
2 | Kultur/Museen/Freizeit | Kultur
3 | Bildung | Bildung
4 | Kinos/Theater/Konzerte | Schauspiel
5 | Apotheken/Gesundheit | Apotheken
6 | Digitale Teilhabe | Digitale Teilhabe
7 | Sport/Bewegung/Tanz | Sport
8 | Mobilität | Mobilität
9 | Sonstiges | Sonstiges


</body>
</html>

**Comment by f1sh1918** [comment]
We should replace the category ids to replace with 10-18 for nuernberg or should we do this in the import?. We need a separate csv file for the categories uploaded to `data.entitlementcard`

**Comment by michael-markl** [comment]
Imo, we can do the mapping in the importer. The current numbers as they are in the table above, are communicated with nürnberg, and they currently use them to maintain their excel sheet.

> We need a separate csv file for the categories uploaded to data.entitlementcard

I think, if we do the mapping in the importer, it's fine?

**Comment by maxammann** [comment]
Feel free to copy the current CSV/Excel and create e.g. a JSON or a different CSV.
That will then be our single source of truth.

I can upload new files to data.entitlementcard.app
