### ISSUE TITLE
Limit length of dynamic data in QR code

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#690]
**Is your feature request related to a problem? Please describe.**
We need to limit the length of dynamic data in the QR code. Right now dynamic data is:

* Name (On average 15chars (US), for Germany we estimate 30 on average)
* ~VAGNumber (probably around 10chars)~ (VAGNumber consists of 8 digits and can be encoded as uint32)

**Describe the solution you'd like**
All other data is of static length. Calculate the worst case data usage for QR code data and then compare it to the current maximum. We use a version 7 QR code with error correction L right now: https://www.qrcode.com/en/about/version.html That means we can store 224 base64 chars right now.

If we do not meet the requirements in terms of space we should truncate the name or abort with an error message: "Name too long, please abbreviate"

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by sarahsporck** [comment]
**Please confirm.**

---

A protobuf message is encoded as follows:
- (in our case) 1 byte for the tag number + x bytes for the data
- if the data has a variable length (submessages, strings or bytes) then there are additionally y bytes for the length
- if data is left out (as in one of) -> no bytes are used for missing data

so i'll write `<bytes_tag> + <bytes_len> + <bytes_data>` if there is a length
messages look like this `<bytes_tag> + <bytes_len>`
otherwise (int32 and uint32) i'll write `<bytes_tag> + <bytes_data>`

**Reference**: 
- https://developers.google.com/protocol-buffers/docs/encoding 
- https://stackoverflow.com/questions/30915704/maximum-serialized-protobuf-message-size

## Calculation

I considered the nuernberg data as it can get larger than tha bavarian data. Also the activation code takes more bytes.
So the protobuf encoded qrcode data consists of:
- qr_code = 1 + 1
    - dynamic_activation_code = 1 + 1
        - pepper = 1 + 1 + 16
        - totpsecret = 1 + 1 + 20
        - ec_signature = 1 + 1 + 32 (?)
        - card_info = 1 + 1
            - name = 1 + 1 + x
            - expiration_date = 1 + 5 
            - extensions = 1 + 1
                - birthday_ext = 1 + 1
                    - birthday = 1 + 10
                - nuernberg_pass_number = 1 + 1
                    - pass_number = 1 + 5

## Results

As @maxamman wrote we have 224 base64 chars. In base64 every 4 chars correspond to 3 bytes resulting in allover `224 / 4 * 3 = 168` bytes.

How many bytes are actually used considering the maximum size minus the name? **109**
Furthermore one byte for the name tag and also maximum 1 byte for the name length.
Therefore the name should be able to hold `168 - 109 - 2 = 57` bytes. 
We encode the QRCode using `btoa` (which actually is deprecated in my node version), which encodes characters in Latin-1.
`Latin-1` uses exactly one byte for each character. Therefore the name can be **57 characters** long, I guess.

**Comment by sarahsporck** [comment]
not sure whether there is a way to test this gracefully though as this consideres the worst worst scenario, where the card has an expiration date and birthday in 2^32 years ^^

**Comment by michael-markl** [comment]
Pretty cool calculations !
I think for expiration_date and pass_number we should use `1+4` as they are int32/uint32; for birthday `1+8` as in int64 or did you take into account the encoding of `varint` which needs some extra bits?
@maxammann needs to confirm the ec_signature length. I remember that it was some pretty large number, but I am not sure.
With your calculations, we could even support handing over an EAK to Mr [Hubert Wolfeschlegelsteinhausenbergerdorff](https://de.wikipedia.org/wiki/Hubert_Blaine_Wolfeschlegelsteinhausenbergerdorff,_Sr.) (who has a 42 chars name and the record for the longest last name :D ). If we can limit the field at 50 chars, we'd be pretty save^^

> not sure whether there is a way to test this gracefully though as this consideres the worst worst scenario, where the card has an expiration date and birthday in 2^32 years ^^

A way to test this, I guess would be to take absurdly high (but still somewhat realistic numbers) fill in a long name, and check whether the resulting byte-string of the encoded QrCodeMessage is above some threshold (of say 168 bytes).

We can also just check the worst case as you did here, and if we're not hitting a problem calculation-wise, we are fine :D (e.g. I would also be fine to limit the name at 35 chars or similar)

**Comment by michael-markl** [comment]
Personally, I'd probably limit the UTF-8 string size of the name to sth like 50 bytes. This kind of depends on the way our protobuf lib encodes the string to UTF-8. If we can't use the same encoding algorithm, I guess taking any utf8 representation should be a good enough approximate, right?

**Comment by sarahsporck** [comment]
> Region and CardType extensions are missing

i did not consider region and card type extension as their bavaria specific. 
And then estimated 
`num_bytes(region_extension, card_type_extension) < num_bytes(birthday_extension, nuernberg_pass_code_extension)`

> It is probably hard to estimate the worst case size consumption of text. For example a 5 character UTF-8 string has different lengths depending on whether it contains 2 byte code points or 1 byte code points.

You're right. Missed that it still is UTF-8 if we put in UTF-8 so then each character can have either 1 or 2 bytes.

> I think for expiration_date and pass_number we should use 1+4 as they are int32/uint32; for birthday 1+8 as in int64 or did you take into account the encoding of varint which needs some extra bits?

int32 can use up to 10 bytes actually as the number is padded "to make it possible to parse them to int64 later" (at least according to this stack overflow post). Although they only use the upper bytes when negative. That only happens if someone is born before 1970, so that is a quite rare situation i'd say.

---

I personally prefer the dynamic calculation better, as the worst case approximation can change over time, when adding other extensions or changing any dataformat. 
It's still fine to limit the number of characters for the name though as it can also mess up the card visualisation in the app. So I'd limit the name to 50 or 45 characters (just to be safe) and validate by the dynamic length.

**Comment by michael-markl** [comment]
>  int32 can use up to 10 bytes actually as the number is padded "to make it possible to parse them to int64 later" (at least according to this stack overflow post). 

Actually 🤓 , according to the protobuf docs, protobuf uses the Varint encoding (which means that every byte is prefixed with a continuation bit which decides whether the next byte still belongs to the encoded number). 

> Although they only use the upper bytes when negative. That only happens if someone is born before 1970, so that is a quite rare situation i'd say.

Good catch! We should use `sint32` instead of `int32` for birthday then, as still a lot of people are born before 1970 :) Paying one/two extra bytes for those born after 1970 is not as bad as paying 5/6/7 extra bytes for those born before.
I think with this modification and assuming all people are born between 1970-70=1900 and 1970+70=2050, the [zig-zag-encoding](https://protobuf.dev/programming-guides/encoding/#signed-ints) takes up at most log_2(2 * 70 * 365)=15.6 bits, and with the extra bits for the varint encoding, we can be pretty sure the birthday field fits into 1(tag)+3 bytes.
Without the zig-zag-encoding and with the "standard" 2s complement encoding of negative numbers, it might actually take 10 bytes as you mentioned.

> I personally prefer the dynamic calculation better, as the worst case approximation can change over time, when adding other extensions or changing any dataformat.
It's still fine to limit the number of characters for the name though as it can also mess up the card visualisation in the app. So I'd limit the name to 50 or 45 characters (just to be safe) and validate by the dynamic length.

Yep, it seems reasonable to implement both checks. However, if the "dynamic limit" is reached, we have to give some weird error to the administration user like "Die Karte enthält zu viele Informationen. Versuchen Sie, den Namen des Inhabers zu kürzen." (which is still okay, I guess)

**Comment by maxammann** [comment]
The thing is that we should evaluate following function on every key press (or at least when the focus goes away from the relevant fields:
```
def is_valid(card):
  return bytes_of_protobuf(card) < 168
```

I guess this should be fine as encoding of data of that size is fast.

So to be sure let's just limit the name length to 50 bytes (that also requires passing the fullname through `TextEncoder` and checking its size).
Additionally to catch future changes we can calculate the size of the protobuf and then compare that to the current maximum according to the QR code version (which will also change maybe!)

**Comment by michael-markl** [comment]
> i did not consider region and card type extension as their bavaria specific.

I am not entirely sure, but I do think, we will put the region extension into nuernberg's qr codes.
That could enable us to actually determine the project from the card.
So we might have roughly 5 bytes less than you calculated.

**Comment by michael-markl** [comment]
I updated the calculation for the nuremberg pass:

```
    qr_code = 1 + 1
        dynamic_activation_code = 1 + 1
            pepper = 1 + 1 + 16
            activation_secret = 1 + 1 + 20
            ec_signature = 1 + 1 + 32 (Let's keep it in the calculations to be able to implement it -- or sth similar -- in the future)
            card_info = 1 + 1
                name = 1 + 1 + x
                expiration_date = 1 + 5
                extensions = 1 + 1
                    birthday_ext = 1 + 1
                        birthday = 1 + 3
                    nuernberg_pass_number = 1 + 1
                        pass_number = 1 + 5
```

1+1 + 1+1 + 1+1+16 + 1+1+20 + 1+1+32 + 1+1 + 1+1+x + 1+5 + 1+1 + 1+1 + 1+3 + 1+1 + 1+5

The bytes here add up to 104 (excluding x)

However, in fact the mentioned QR code version 7 with L error correction can only hold 154 bytes!! (it can hold 224 alphanumeric characters, but only uppercase; so we could not use base 64 -- we use binary encoding #775 )

By now, we use Version 8 with M error correction (at least for the dynamic activation and static verification qr codes; we use auto version in frontend with L error correction), which can even only hold 152 bytes!!
Therefore, x should be at most `152-104=48` bytes.
