### ISSUE TITLE
[Application] Inform the applicant about the application result

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/entitlementcard#838]
**Is your feature request related to a problem? Please describe.**
When the application process is finished the applicant should be informed whether the application was rejected (otherwise he might never know).
This might need to be discussed with the StMas.

**Describe the solution you'd like**
An e-mail is sent to the applicant, that the application was rejected.

**Describe alternatives you've considered**
The Mitarbeiter der Kommune can decide him/herself whether an e-mail should be sent.

**Additional context**

**Comment by michael-markl** [comment]
Well, we currently don't have contact data for every region (and likely won't have it in the near future). Probably we have to refer him to the website of his region if he wants to directly get into contact with someone. (see here: https://www.lbe.bayern.de/engagement-anerkennen/ehrenamtskarte/antraege/index.php)

**Comment by sarahsporck** [comment]
The websites are in fact already in the database (region -> website). Furthermore, the websites I checked out also list a contact phone number or email. I guess we refer the user to there :)

**Comment by f1sh1918** [comment]
Well its actually a lot of work to collect these mail information. I think we could maybe send an email to the applicant when the card was created. (This can be set in the application next to the delete button) Even better would be to have a button on the application "Create Card" and pass the information to the create card view. Currently the process is very error prone, since the user has to check the application, note down surname, name and type of card and then switch to the card creation and type it in.

**Comment by sarahsporck** [comment]
I think you misunderstood there. The idea was to just add a link to the website in the email. And the main idea behind sending the email was to inform the applicant about whether the application was rejected. As otherwise the applicant may never know. 
One issue here might be that there already is a workflow when the application is rejected, where the "mitarbeiter of the region" calls the user or writes an email by hand. 
When the application is successful the user should already receive a letter/email with the anmeldecode, so it might not be necessary to send an email in this case.

**Comment by f1sh1918** [comment]
this issue was rejected since it's not yet a requirement by the customer
